project:
  type: website
  output-dir: docs

website:
  title: "RDKit blog"
  site-url: https://greglandrum.github.io/rdkit-blog/
  description: "RDKit experiments, tips, and tutorials"
  favicon: posts/icons/favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rdkit/rdkit
      - icon: twitter
        href: https://bsky.app/profile/rdkit.bsky.social
      - icon: linkedin
        href: https://www.linkedin.com/groups/8192558/
      - icon: rss
        href: index.xml
  page-footer:
    left: |
      Copyright (C) 2025 Greg Landrum
    right: |
      [![](https://www.rdkit.org/logo.small.png){fig-alt="RDKit" width=64px}](https://www.rdkit.org)

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

comments:
  utterances:
    repo: greglandrum/rdkit-blog

execute:
  freeze: auto

